### ISSUE TITLE
Custom Tags dont persist

### ISSUE THREAD

**Issue by mike391** [linuxserver/docker-diskover#27]
Custom tags in diskover-web are removed if the container is stopped and started again.  Editing /config/customtags.txt has no effect on the custom tags either.  

Custom tags can be seen in the Admin panel (top right link)

**Comment by christronyxyocum** [comment]
They will: https://github.com/linuxserver/docker-diskover/pull/26

**Comment by christronyxyocum** [comment]
Fixes have been merged and the updated image has been built so you should be able to pull it and recreate the container.
