### ISSUE TITLE
Diskover tries to connect to `localhost`, even though `ES_HOST` is set.

### ISSUE THREAD

**Issue by jtagcat** [linuxserver/docker-diskover#52]
## Current Behavior
After login, this page is presented:
![image](https://user-images.githubusercontent.com/38327267/175190837-4a7e7af8-6636-4f2d-95f9-5d23a1a26c2f.png)

***

Why does the docker-compose suggest exposing elasticsearch globally? Shouldn't it be exposed only to diskover, internally?

**Comment by jtagcat** [comment]
unstale shrug

**Comment by j0nnymoe** [comment]
The readme mentions that you need to manually change the discover web config file.
